name = "BoundaryIntegral"
uuid = "c5e3a73d-e4f2-41fa-921b-bb4fcd908115"
version = "1.0.0-DEV"
authors = ["Xuanzhao Gao <xgao@flatironinstitute.org> and contributors"]

[deps]
FMM2D = "2d63477d-9690-4b75-bcc1-c3461d43fecc"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
SparseMatricesCOO = "fa32481b-f100-4b48-8dc8-c62f61b13870"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
GLMakieExt = ["GLMakie"]

[compat]
FMM2D = "0.2.0"
FastGaussQuadrature = "1.1.0"
GLMakie = "0.13.6"
IterativeSolvers = "0.9.4"
KernelAbstractions = "0.9.39"
LinearAlgebra = "1.12.0"
LinearMaps = "3.11.4"
OMEinsum = "0.9.2"
SparseMatricesCOO = "0.2.6"
julia = "1.10, 1.11, 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
