name = "BoundaryIntegral"
uuid = "c5e3a73d-e4f2-41fa-921b-bb4fcd908115"
version = "1.0.0-DEV"
authors = ["Xuanzhao Gao <xgao@flatironinstitute.org> and contributors"]

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockSparseArrays = "2c9a651f-6452-4ace-a6ac-809f4280fbb4"
FMM2D = "2d63477d-9690-4b75-bcc1-c3461d43fecc"
FMM3D = "1e13804c-f9b7-11ea-0ef0-29f3b1745df8"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCOO = "fa32481b-f100-4b48-8dc8-c62f61b13870"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
GLMakieExt = ["GLMakie"]

[compat]
BlockArrays = "1.9.3"
BlockSparseArrays = "0.10.17"
FMM2D = "0.2.0"
FMM3D = "1.0.1"
FastGaussQuadrature = "1.1.0"
GLMakie = "0.13.6"
Krylov = "0.10.2"
LinearAlgebra = "1.12.0"
LinearMaps = "3.11.4"
Roots = "2.2.10"
SparseArrays = "1.12.0"
SparseMatricesCOO = "0.2.6"
julia = "1.10, 1.11, 1.12"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
